### ISSUE TITLE
Idea: Create a newsfeed/changelog style page to summarize recent guideline changes that were done inside Discord

### ISSUE THREAD

**Issue by kaizensh** [stashapp/StashDB-Docs#1]
In an act of ensuring information is not silo'd and that ground rules are always known, I think it would be useful to incorporate some sort of page that mimics a newsfeed/blog/changelog. This would contain all of the important changes that were made/voted on to StashDB guidelines and fundamentals via the Discord [channel](https://ptb.discord.com/channels/559159668438728723/967033917196632084). 

Posts/entries could include a structure such as:
- Timestamp of changes
- Quick summary of old methodology/guidelines/practices
- The new or adjustment of said above ^
- Why the change
- How to move forward/transition from said changes
- Links to deeper documentation of said change

**Comment by AdultSun** [comment]
There was a suggestion a while ago for a similar newsfeed/changelog for big changes on StashDB (not just dev updates but notable edits/submissions/projects as well), hosted within StashDB somewhere. I think it makes sense to do something similar here for the guidelines at least in the meantime. I'll have to think about the best place to put it. We may even want to put the most recent change on the homepage somewhere for greater visibility, with a link to the older updates as well.

**Comment by AdultSun** [comment]
Coming back to this idea, I'd be interested to see/hear pitches on how best to organize and format a changelog on the website. Threading everything on a single page seems too unwieldy. I'm not sure if we split them up into folders by month/year would be any better. Would we rather just limit the visible changelog to the last X number of updates instead? I'm not sure what the typical best practices for something like this would be.

**Comment by DogmaDragon** [comment]
For changelog, I think just creating a static list with links to PRs would work. They could be broken up by dates (limited to year/month). Similar to how Stash handles the changelog <https://github.com/stashapp/stash/blob/develop/ui/v2.5/src/docs/en/Changelog/v0170.md>
The advantage of this is that you don't need to re-type/cope&paste every change, you just link to the actual pull request with the title of the guideline. 

It can be split into multiple files by YYYY-MM, but I don't think we generate so many changes that one single list would be too big to just list everything into a single file. 

One change for this that would be required is for you to create the pull request for the change and merge it instead of just editing this repository directly. 

For the newsfeed, I think the thread system on Discord works great. If someone was gone for x days, all the new submissions in #stashdb-guidelines the user missed will be marked as unread. I don't think any replacement here would be superior to that. And the changelog would provide a quick overview. For arguments that Discord shouldn't be the only place for information, I agree, but at the moment we treat Discord as a primary medium both for voting and any disputes that arise from guidelines.

**Comment by AdultSun** [comment]
I'll have to do some experimenting to figure out how best to adjust my workflow for that. I'm already using VS Code for editing so it shouldn't be too difficult to start pushing commits and PRs from there too.
