### ISSUE TITLE
[Update] Better Organize Guideline Sections

### ISSUE THREAD

**Issue by AdultSun** [stashapp/StashDB-Docs#30]
I have one particular subject in mind for this topic, but if we're going to move a bunch of things around we might as well collect all our concerns here under a more generalized subject-line. Hopefully if we get a good idea of what changes we want made, ideally we'll only have to move everything **once**.

One thing I've found inconvenient about the current organization of our guideline pages is that so many sub-headings aren't exposed to the sidebar. The only way to navigate to, for example, our "Amateur Studio" section is to click on "Adding Studios" in the sidebar and then click "Amateur Studios" in the auto-generated table of contents. And that's only if I already know which heading it's under. Otherwise I'd have to browse through the higher-level "Studios" heading first or try to use the search bar at the top.

I wasn't sure before, but it looks like it is possible to have multiple nested levels in the sidebar. For example, just-the-docs (our Jekyll theme) has [this page](https://just-the-docs.github.io/just-the-docs/docs/ui-components/code/line-numbers/) nested three levels down. This wasn't possible in the simple GitHub wiki we started with, so the new site just inherited that "everything on one page" approach.

It'll be a pain to rearrange everything, but I think it would look cleaner and be easier to navigate if each section had its own page so everything can be listed in the sidebar. This will take a while to accomplish too so I'd like to have some agreement on the best approach for a project like this first before we commit to anything. Again, share any other ideas in this thread as well. It should be easier to tackle everything at once instead of changing everything around several times over.

**Comment by echo6ix** [comment]
I would suggest organizing the documentation's primary headings based on the semantic structure of StashDB's navbar because it's intuitive both for the end-user looking at the documentation and the document writers maintaining the documentation.

When an end-user realizes the docs structure mirrors the the structure of StashDB they will know precisely where to look for the information they require. When the docs maintainers need to edit or add new information, there will be no guesswork or misplacement of headings because they know it must follow the semantic structure of the StashDB UI.

### Primary headings (per the StashDB navbar)
1. Performers
2. Scenes
3. Studios
4. Tags
5. Edits
6. Drafts
7. User section
8. Search
9. FAQ
10. Terminology

If StashDB adds a new heading it's intuitive where it should be placed in the above structure. I.E., if we wanted to add a section for the "Home" page, it would intuitively become the first heading before _performers_: 1. Home, 2. Performers, 3. Studios, etc.

### Subheadings
Each primary section would contain parallel constituents that also follow the flow the the StashDB UI.

1. Performers
  a. Creating performers
    1. Personal information
       a. Name
       b. Disambiguation
       c. Aliases
       d. Gender
       e. ...
    2. Tattoos and Piercings
      a. ...
    3. Links
      a. ...
    4. Images
      a. ...
    5. Confirm
2. Scenes
3. Studios
4. etc

What I'm not suggesting is that every sub-subsection from StashDB must exist in the docs because some sub-sections, such as _[Performer] Gender_, may require no explanation. But for the sub-sections that do require explaining, they should match the title and placement of the StashDB elements.

Side note: I would also stress that there is no point in having docs if the people who really need them don't know they exist. A link to the documentation belongs on the StashDB navbar https://github.com/stashapp/stash-box/issues/512

![192161163-5e701e31-e3cd-4610-af26-47627fcca2ea](https://user-images.githubusercontent.com/37937507/208277339-1c86026d-a350-4f63-b022-a5a0b57679ea.png)

**Comment by AdultSun** [comment]
I'm not sure what you have in mind exactly for primary headings 5-10, for me those don't sound like substantial enough topics to warrant their own primary headings. We've already got Performers / Scenes / Studios / Tags in the correct order, the changelog should stay at the bottom, and I guess we could move our "Getting Started" sections (essentially serves the same function as an FAQ just in a different format) below Tags where "Guide to Scraping" is now. It's not as prominent of a position as its current spot though, but maybe a more prominent link to it on the homepage would work instead.

I can see the value in mirroring the arrangement as much as possible down to the subheadings too, I think I'd have to work on finding exactly where everything should go before I'd know where the shortcomings of that arrangement would be. It could work. To keep things in the right spot with how Jekyll works (you have to give each page a discrete number) we'd likely have to create a bunch of placeholder pages. We can easily hide those empty pages from view and that approach would also help us to identify and log subjects that aren't covered yet.

The last point is putting a link to the guidelines in StashDB's header, which absolutely should be done. But, adding simple links like that should still be seen as just the first step. Part of our reasoning for using Jekyll is that it might make it easier to automatically extract language from those simple markdown files and embed relevant guidelines throughout StashDB. It should be convenient for contributors to find quick explanations in-line somewhere, "This is what we expect for this field," maybe some kind of tooltip system. It'll be difficult to make that info ready at hand without cluttering everything up, but that's the eventual goal in my mind. I don't know how any of that would work on a technical level, but I can see how keeping the guidelines in the same relative order as StashDB could help the devs keep track of everything while linking the two together.

**Comment by Valmox** [comment]
I like echo6ix's suggestion of structure, with the exception of Getting Started/FAQ. I think this should stay at the top considering the nature of the information it contains.

I agree about prioritising a link in the menu, with a view to implementing tooltips.

Ultimately, even if the sections are relatively short, there is likely value in (echo6ix's) 5-8 in my opinion. It could explain how people can use these sections and give us somewhere to point people to in Discord (eg, "how do I edit my submission"). This could have changed, but I used to see people not realising that they could edit drafts (!) before submitting. #9 should probably be in Getting Started (for which I prefer the existing name), and #10 is just for whatever coms in the future.

**Comment by AdultSun** [comment]
Forgot to close this issue, already completed with PR #45
